addons:
  sonarcloud:
    organization: "rondoublec"
#    token:
#      secure: "1ad579afa992a0a2494f932549fb215381922f6c"


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -DskipTests -Dsonar.projectKey=Rondoublec_myerp09 -Dsonar.login=89dd751f43bb6c8648e0c961baf0e3a08d994178
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Rondoublec_myerp09 -Dsonar.login=89dd751f43bb6c8648e0c961baf0e3a08d994178
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Rondoublec_myerp09 -Dsonar.login=1ad579afa992a0a2494f932549fb215381922f6c
