language: java
jdk:
  - openjdk8

services:
  - postgresql

addons:
  sonarcloud:
    organization: "rondoublec"
#    token:
#      secure: "1ad579afa992a0a2494f932549fb215381922f6c"

before_script:
  - psql -c 'create database db_myerp;' -U postgres
  - psql -c "create user usr_myerp with password 'myerp';" -U postgres
  - psql -c 'grant all privileges on database db_myerp to usr_myerp;' -U postgres

script:
  - psql -f 'init_db_myerp_test.sql' -U postgres
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Rondoublec_myerp09 -Dsonar.login=1ad579afa992a0a2494f932549fb215381922f6c
